apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: rhacm-hub-banner
spec:
  backgroundColor: "#b71c1c"        # dark red for HUB
  color: "#ffffff"
  location: BannerTop
  text: "RHACM HUB – hub.example.com"
