- hosts: localhost
  gather_facts: false

  collections:
    - community.general   # read_csv comes from here

  vars_files:
    - vars/cluster.yml

  vars:
    # Input data
    csv_path: nodes.csv
    output_dir: out

    # Global BMC credentials (same for all nodes in your case)
    bmc_username: root
    bmc_password: changeme

    # AgentClusterInstall sizing
    multicluster_engine_managed_cluster_control_plane_agents: 3
    multicluster_engine_managed_cluster_worker_agents: 3

    # Global pull secret (Docker config JSON)
    redhat_cloud_pull_secret: 'REPLACE_ME'

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Read nodes from CSV
      community.general.read_csv:
        path: "{{ csv_path }}"
      register: nodes

    # --------------------
    # Cluster + InfraEnv YAMLs
    # --------------------
    - name: Render cluster and infraenv templates
      template:
        src: "templates/{{ item.src }}"
        dest: "{{ output_dir }}/{{ item.dest }}"
      loop:
        - { src: "cluster-namespace.yaml.j2",           dest: "cluster-namespace.yaml" }
        - { src: "cluster-deployment.yaml.j2",          dest: "cluster-deployment.yaml" }
        - { src: "managedcluster.yaml.j2",              dest: "managedcluster.yaml" }
        - { src: "klusterletaddonconfig.yaml.j2",       dest: "klusterletaddonconfig.yaml" }
        - { src: "cluster-agentclusterinstall.yaml.j2", dest: "cluster-agentclusterinstall.yaml" }
        - { src: "cluster-infraenv-ns.yaml.j2",         dest: "cluster-infraenv-ns.yaml" }
        - { src: "cluster-infraenv.yaml.j2",            dest: "cluster-infraenv.yaml" }
        - { src: "pullsecret-cluster-secret.yaml.j2",   dest: "pullsecret-cluster-secret.yaml" }

    # --------------------
    # Node / hardware level
    # --------------------
    - name: Generate BareMetalHost YAML per node
      template:
        src: templates/baremetalhost.yaml.j2
        dest: "{{ output_dir }}/baremetalhost-{{ item['Red Hat Core OS'] }}.yaml"
      loop: "{{ nodes.list }}"
      loop_control:
        label: "{{ item['Red Hat Core OS'] }}"
      vars:
        rhcos_name: "{{ item['Red Hat Core OS'] }}"
        ilo_ip: "{{ item['iLO IP'] }}"
        ilo_mac: "{{ item['ILO MAC'] }}"
        # Role column in CSV; defaults to worker if missing
        role: "{{ (item['Role'] | default('worker')) | lower }}"

    - name: Generate BMC Secret YAML for all nodes (multi-doc)
      template:
        src: templates/bmc-secret.yaml.j2
        dest: "{{ output_dir }}/bmc-secret.yaml"
