- name: Generate MCE yamls
  hosts: localhost
  gather_facts: false

  collections:
    - community.general

  vars_files:
    - vars/cluster.yml

  vars:
    # CSV file is named after the cluster, e.g. cl-dc3-qdt-01.csv
    csv_path: "{{ multicluster_engine_managed_cluster_baremetal.cluster_name }}.csv"

    # Primary output directory (cluster dir), e.g. cl-dc3-qdt-01/
    output_dir: "{{ multicluster_engine_managed_cluster_baremetal.cluster_name }}"

    # Directory for remaining nodes, e.g. cl-dc3-qdt-01-remaining-nodes/
    remaining_output_dir: "{{ multicluster_engine_managed_cluster_baremetal.cluster_name }}-remaining-nodes"

    # Global BMC credentials (same for all nodes in your case)
    bmc_username: root
    bmc_password: changeme

    # AgentClusterInstall sizing (used in cluster-agentclusterinstall.yaml.j2)
    multicluster_engine_managed_cluster_control_plane_agents: 3
    multicluster_engine_managed_cluster_worker_agents: 3

    # Global pull secret (Docker config JSON) used in pullsecret-cluster-secret.yaml.j2
    redhat_cloud_pull_secret: 'REPLACE_ME'

  pre_tasks:
    - name: Derive cluster variables
      ansible.builtin.set_fact:
        # Generic alias for templates (cluster-level values)
        multicluster_engine_managed_cluster: "{{ multicluster_engine_managed_cluster_baremetal }}"
        # Convenience variables
        cluster_namespace: "{{ multicluster_engine_managed_cluster_baremetal.cluster_name }}"
        infraenv_namespace: "{{ multicluster_engine_managed_cluster_baremetal.cluster_name }}-infraenv"

    - name: Ensure primary output directory exists
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0775'

    - name: Ensure remaining-nodes output directory exists
      ansible.builtin.file:
        path: "{{ remaining_output_dir }}"
        state: directory
        mode: '0775'

    - name: Read nodes from CSV (raw, with explicit fieldnames)
      community.general.read_csv:
        path: "{{ csv_path }}"
        delimiter: ','
        skipinitialspace: true
        fieldnames:
          - Worker nodes
          - Red Hat Core OS
          - Role
          - iLO IP
          - Management IP
          - vMotion IP
          - ILO MAC
          - BMC57416 NIC0
          - BMC57416 NIC1
          - SFC X2522 NIC0
          - SFC X2522 NIC1
      register: nodes_raw

    - name: Filter valid node rows (drop junk/header rows)
      ansible.builtin.set_fact:
        nodes: >-
          {{
            nodes_raw.list
            | selectattr('Management IP', 'match', '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$')
            | list
          }}

  tasks:
    # --------------------
    # Cluster-level YAMLs (no per-node data)
    # --------------------
    - name: Render cluster-level templates
      ansible.builtin.template:
        src: "templates/{{ item }}.yaml.j2"
        dest: "{{ output_dir }}/{{ item }}.yaml"
        mode: '0664'
      loop:
        - cluster-infraenv-ns
        - cluster-infraenv
        - cluster-agentclusterinstall
        - pullsecret-cluster-secret
        - install-config

    - name: Generate BMC Secret YAML (single shared secret)
      ansible.builtin.template:
        src: templates/bmc-secret.yaml.j2
        dest: "{{ output_dir }}/bmc-secret.yaml"
        mode: '0664'

    # --------------------
    # Node / hardware-level YAMLs
    # Rule (index-based, no Role column in CSV):
    #   index 0,1,2 -> masters in primary dir
    #   index 3,4,5 -> workers in primary dir
    #   index >= 6  -> workers in remaining-nodes dir
    # --------------------
    - name: Generate BareMetalHost YAML for all nodes (split by index)
      ansible.builtin.template:
        src: templates/baremetalhost.yaml.j2
        dest: >-
          {{
            (ansible_loop.index0 < 6)
            | ternary(output_dir, remaining_output_dir)
          }}/baremetalhost-{{ item['Red Hat Core OS'] }}.yaml
        mode: '0664'
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item['Red Hat Core OS'] }}"
        extended: true
      vars:
        rhcos_name: "{{ item['Red Hat Core OS'] }}"
        ilo_ip: "{{ item['iLO IP'] }}"
        ilo_mac: "{{ item['ILO MAC'] }}"
        # First 3 nodes are masters, everything else is worker (for labels in BMH)
        role: "{{ 'master' if ansible_loop.index0 < 3 else 'worker' }}"

    - name: Generate NMStateConfig YAML for all nodes (split by index)
      ansible.builtin.template:
        src: templates/nmstateconfig.yaml.j2
        dest: >-
          {{
            (ansible_loop.index0 < 6)
            | ternary(output_dir, remaining_output_dir)
          }}/nmstateconfig-{{ item['Red Hat Core OS'] }}.yaml
        mode: '0664'
      loop: "{{ nodes }}"
      loop_control:
        label: "{{ item['Red Hat Core OS'] }}"
        extended: true
      vars:
        rhcos_name: "{{ item['Red Hat Core OS'] }}"
        mgmt_ip: "{{ item['Management IP'] }}"
        bmc57416_nic0_mac: "{{ item['BMC57416 NIC0'] }}"
        bmc57416_nic1_mac: "{{ item['BMC57416 NIC1'] }}"
        sfc_x2522_nic0_mac: "{{ item['SFC X2522 NIC0'] }}"
        sfc_x2522_nic1_mac: "{{ item['SFC X2522 NIC1'] }}"
