- name: Generate MCE yamls
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/cluster.yml

  vars:
    # Input data
    csv_path: nodes.csv
    output_dir: out

    # Global BMC credentials (same for all nodes in your case)
    bmc_username: root
    bmc_password: changeme

    # AgentClusterInstall sizing
    multicluster_engine_managed_cluster_control_plane_agents: 3
    multicluster_engine_managed_cluster_worker_agents: 3

    # Global pull secret (Docker config JSON)
    redhat_cloud_pull_secret: 'REPLACE_ME'

  tasks:
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory
        mode: '666'

    - name: Read nodes from CSV
      community.general.read_csv:
        path: "{{ csv_path }}"
      register: nodes

    # --------------------
    # Cluster + InfraEnv YAMLs (single simple loop)
    # --------------------
    - name: Render cluster and infraenv templates
      ansible.builtin.template:
        src: "templates/{{ item }}.yaml.j2"
        dest: "{{ output_dir }}/{{ item }}.yaml"
        mode: '666'
      loop:
        - cluster-namespace
        - cluster-deployment
        - managedcluster
        - klusterletaddonconfig
        - cluster-agentclusterinstall
        - cluster-infraenv-ns
        - cluster-infraenv
        - pullsecret-cluster-secret

    # --------------------
    # Node / hardware level
    # --------------------
    - name: Generate BareMetalHost YAML per node
      ansible.builtin.template:
        src: templates/baremetalhost.yaml.j2
        dest: "{{ output_dir }}/baremetalhost-{{ item['Red Hat Core OS'] }}.yaml"
        mode: '666'
      loop: "{{ nodes.list }}"
      loop_control:
        label: "{{ item['Red Hat Core OS'] }}"
      vars:
        rhcos_name: "{{ item['Red Hat Core OS'] }}"
        ilo_ip: "{{ item['iLO IP'] }}"
        ilo_mac: "{{ item['ILO MAC'] }}"
        # Role column in CSV; defaults to worker if missing
        role: "{{ (item['Role'] | default('worker')) | lower }}"

    - name: Generate BMC Secret YAML for all nodes (multi-doc)
      ansible.builtin.template:
        src: templates/bmc-secret.yaml.j2
        dest: "{{ output_dir }}/bmc-secret.yaml"
        mode: '666'
