- name: Generate NetworkMap yamls
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/cudn.yml   # reuse same CSV + add networkmap_* vars here

  tasks:
    - name: Ensure NetworkMap output directory exists
      ansible.builtin.file:
        path: "{{ networkmap_output_dir }}"
        state: directory
        mode: '0755'

    - name: Read CUDN / network entries from CSV
      community.general.read_csv:
        path: "{{ cudn_csv_path }}"
      register: cudn_csv

    - name: Build items for NetworkMap (reuse CUDN naming + VLAN)
      ansible.builtin.set_fact:
        cudn_items: >-
          {{ (cudn_items | default([])) + [ {
              'name': (
                item['Name']
                | lower
                | regex_replace('[^0-9a-zA-Z]+', '-')
                | regex_replace('^-+', '')
                | regex_replace('-+$', '')
              ),
              'vlan_id': (
                item['VLAN ID']
                | default('')
                | regex_search('([0-9]+)')
                | default('0', true)
                | int
              ),
              'source_name': item['Name']
            } ] }}
      loop: "{{ cudn_csv.list }}"
      loop_control:
        label: "{{ item['Name'] | default('UNKNOWN') }}"

    - name: Fail if no valid NetworkMap rows were found
      ansible.builtin.fail:
        msg: "No valid rows were found in {{ cudn_csv_path }} to build NetworkMaps"
      when: cudn_items | default([]) | length == 0

    - name: Render one NetworkMap manifest per VLAN
      ansible.builtin.template:
        src: templates/networkmap.yaml.j2
        dest: "{{ networkmap_output_dir }}/{{ item.name }}-map.yaml"
        mode: '0644'
      loop: "{{ cudn_items }}"
      loop_control:
        label: "{{ item.name }}-map"
